import "./globals.css";
import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import Tailwind from "primereact/passthrough/tailwind";
import { Inter } from "next/font/google";
import { usePassThrough } from "primereact/passthrough";
import PrimeProvider from "./primeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeProvider>{children}</PrimeProvider>
      </body>
    </html>
  );
}
